import os

RESSOURCES_DIR = 'res'

#MEDIALOCATION = 'medialocation'
MEDIALOCATION = 'medialocate'
MEDIALOCATION_DIR = f'.{MEDIALOCATION}'
MEDIALOCATION_STORE_NAME = f'{MEDIALOCATION}.json'
MEDIALOCATION_STORE_PATH = os.path.join(MEDIALOCATION_DIR, MEDIALOCATION_STORE_NAME)
#MEDIALOCATION_RES_DIR = os.path.join(RESSOURCES_DIR, MEDIALOCATION)
MEDIALOCATION_RES_DIR = RESSOURCES_DIR
MEDIALOCATION_PAGE = f'{MEDIALOCATION}.html'
MEDIALOCATION_PAGE_DATA = f'{MEDIALOCATION}.js'
MEDIALOCATION_PAGE_PROLOG = f'{MEDIALOCATION}_prolog.html'
MEDIALOCATION_PAGE_EPILOG = f'{MEDIALOCATION}_epilog.html'

MEDIAGROUPS = 'mediagroups'
MEDIAGROUPS_STORE_NAME = f'{MEDIAGROUPS}.json'
MEDIAGROUPS_STORE_PATH = os.path.join(MEDIALOCATION_DIR, MEDIAGROUPS_STORE_NAME)
MEDIAGROUPS_RES_DIR = os.path.join(RESSOURCES_DIR, MEDIAGROUPS)

MEDIAPROXIES = 'mediaproxies'
MEDIAPROXIES_STORE_NAME = f'{MEDIAPROXIES}.json'
MEDIAPROXIES_STORE_PATH = os.path.join(MEDIALOCATION_DIR, MEDIAPROXIES_STORE_NAME)
MEDIAPROXIES_RES_DIR = os.path.join(RESSOURCES_DIR, MEDIAPROXIES)
