repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 24.10.0  # Updated to match poetry
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1  # Updated to match poetry
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        exclude: ^(tests/|conftest\.py)

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0  # Updated to match poetry
    hooks:
    -   id: mypy
        exclude: ^(tests/|conftest\.py)
        additional_dependencies:
        - types-PyYAML

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest with coverage
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
        args: [
            "--cov=src/medialocate",
            "--cov-report=term-missing",
            "--cov-fail-under=80"
        ]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        # Security checks less relevant for tests
        exclude: ^(test/|tests/)
