[tool.poetry]
name = "medialocate"
version = "0.1.0"
description = "A tool for analyzing and grouping media files based on geolocation data"
authors = ["jmarc580625 <jmarc580625+github@gmail.com>"]
readme = "README.md"
packages = [{include = "medialocate", from = "src"}]
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Multimedia :: Graphics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[tool.poetry.urls]
Homepage = "https://github.com/jmarc580625/medialocate"
Repository = "https://github.com/jmarc580625/medialocate"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
pillow = ">=10.0.0"
exif = ">=1.6.0"
geopy = ">=2.4.0"
pydantic = "^2.7.0"
devtools = "^0.12.2"
loguru = "^0.7.2"
chromadb = "^0.4.24"
fastapi = "^0.110.1"
uvicorn = "^0.27.1"
httpx = "^0.27.0"
typer = "^0.9.0"
streamlit = "^1.32.1"
pyyaml = "^6.0.1"
pygraphviz = "^1.12"
grandalf = "^0.8"
sse-starlette = "^2.1.0"
tabulate = "^0.9.0"
tiktoken = "^0.7.0"

[tool.poetry.group.transformers]  # Install : poetry install --with transformers 
optional = true

[tool.poetry.group.demos]  # Install : poetry install --with demos 
optional = true

[tool.poetry.group.dev.dependencies]
pytest = ">=7.4.0"
pytest-cov = ">=4.1.0"
black = ">=23.7.0"
flake8 = ">=6.1.0"
mypy = ">=1.4.1"
bandit = ">=1.7.5"
pre-commit = ">=3.3.3"
types-Pillow = ">=10.0.0"

[tool.poetry.scripts]
medialocate = "medialocate.cli:main"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --cov=src --cov-report=term-missing"
testpaths = [
    "tests",
]

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "pass",
    "raise ImportError",
]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

[tool.black]
line-length = 100
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'

[tool.ruff]
select = ["E", "F", "I"]
ignore = ["E501"]
builtins = ["ic", "debug"]
line-length = 100
target-version = "py39"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
