[tool.poetry]
name = "medialocate"
version = "0.1.0"
description = ""
authors = ["jmarc580625 <jmarc580625+github@gmail.com>"]
readme = "README.md"
#packages = [{include = "medialocate"}]

[tool.poetry.urls]
Homepage = "https://github.com/jmarc580625/medialocate"
Repository = "https://github.com/jmarc580625/medialocate"


[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pydantic = "^2.7.0"
devtools = "^0.12.2"
loguru = "^0.7.2"
chromadb = "^0.4.24"
fastapi = "^0.110.1"
uvicorn = "^0.27.1"
httpx = "^0.27.0"
typer = "^0.9.0"
streamlit = "^1.32.1"
pyyaml = "^6.0.1"
pygraphviz = "^1.12"
grandalf = "^0.8"
sse-starlette = "^2.1.0"
tabulate = "^0.9.0"
tiktoken = "^0.7.0"

[tool.poetry.group.transformers]  # Install : poetry install --with transformers 
optional = true

[tool.poetry.group.demos]  # Install : poetry install --with demos 
optional = true

[tool.ruff]
select = [ "E", "F", "I" ]
ignore = [ "E501" ]
builtins = ["ic", "debug"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

